version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: usbdb
      MYSQL_USER: root
      MYSQL_PASSWORD: your_db_password
      MYSQL_ROOT_PASSWORD: your_db_root_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: your_db_root_password
